version: "3"

services:
  servidor:
    build:
      context: ./servidor
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www
      - ./servidor/nginx.conf:/etc/nginx/nginx.conf
      - ./servidor/sites/:/etc/nginx/sites-available
      - ./servidor/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-app

  php-app:
    build:
      context: ./php-app
    volumes:
      - ../src:/var/www

  bd:
    build:
      context: ./bd
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./bd/data.sql:/docker-entrypoint-initdb.d/data.sql